// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: v1/demo.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StreamGreeterService_Greet_FullMethodName = "/proto.v1.StreamGreeterService/Greet"
)

// StreamGreeterServiceClient is the client API for StreamGreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamGreeterServiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type streamGreeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreeterServiceClient(cc grpc.ClientConnInterface) StreamGreeterServiceClient {
	return &streamGreeterServiceClient{cc}
}

func (c *streamGreeterServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, StreamGreeterService_Greet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamGreeterServiceServer is the server API for StreamGreeterService service.
// All implementations must embed UnimplementedStreamGreeterServiceServer
// for forward compatibility
type StreamGreeterServiceServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedStreamGreeterServiceServer()
}

// UnimplementedStreamGreeterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamGreeterServiceServer struct {
}

func (UnimplementedStreamGreeterServiceServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedStreamGreeterServiceServer) mustEmbedUnimplementedStreamGreeterServiceServer() {}

// UnsafeStreamGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamGreeterServiceServer will
// result in compilation errors.
type UnsafeStreamGreeterServiceServer interface {
	mustEmbedUnimplementedStreamGreeterServiceServer()
}

func RegisterStreamGreeterServiceServer(s grpc.ServiceRegistrar, srv StreamGreeterServiceServer) {
	s.RegisterService(&StreamGreeterService_ServiceDesc, srv)
}

func _StreamGreeterService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeterService_Greet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamGreeterService_ServiceDesc is the grpc.ServiceDesc for StreamGreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamGreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.StreamGreeterService",
	HandlerType: (*StreamGreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _StreamGreeterService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/demo.proto",
}
