definitions:
  serializer.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      error:
        type: string
      msg:
        type: string
    type: object
  serializer.UserToken:
    properties:
      avatar:
        type: string
      created_at:
        type: integer
      expires_at:
        type: integer
      id:
        type: integer
      nickname:
        type: string
      status:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
host: localhost
info:
  contact:
    email: 2724445401@qq.com
    name: kirito
    url: http://localhost/swagger/index.html
  description: 接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: "1.0"
paths:
  /api/v1/ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 接口调试
      tags:
      - Ping
  /api/v1/user/login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.UserToken'
      summary: 用户登录接口
      tags:
      - User
swagger: "2.0"
